Members.js
app.js
middleware/logger.js
package.json
routes/api/members.js
templates/about.html
templates/css/style.css
templates/index.html

Set up base code after clearing up repository
close #7

Initial code base

---

app.js
templates/models/article.js

set up local mongodb server and connected to app.js using mongoose, connection verified to local db name 'sadb'
close #8

setup database and access through mongoose

---

.gitignore
README.md
app.js
package.json
templates/login-success.html
templates/login.html
templates/models/Users.js
test/retrieve_test.js
test/save_test.js
usermodel.js

- set up database for storing user credential
- update readme
- request id and password from user
- send user id and password from client to server
- verify if user id is duplicating
close #14 #18 #19 #20 #21

User management

---

.gitignore
README.md
app.js
client/css/index.css
client/index.html
client/index.jsx
db/database.js
package.json
test/user.js
webpack.config.js

branch for #30 was incorrectly created
This pr is necessary to merge changes for #30 to master

Merging #30

---

app.js
client/index.jsx
client/signup.jsx
db/celebrity.js
db/database.js
routes/login.js

Celebrity list initiate automatically when database connection is established 
close #37

adding list of celebrities when db is initiated

---

client/components/findStar.jsx
client/css/index.css
routes/Favorite.js

fetch call handler for "removeFav" is added in db/favorite.
when you hit remove button beside fav button it removes that celebrity from the favourite list if it had been added to the list

#45: removing a celebrity from the list

---

client/components/findStar.jsx
client/signin.jsx
client/signup.jsx

use onClick instead of the form onSubmit, 
change function name from handleSubmit to handleFavorite

#51 : Rewrite Favorite Function

---

client/components/myStar.jsx
routes/Favourite.js

retrieve favourite list from database and display

#57 : Retrieve favourite list from database

---

client/components/findStar.jsx
client/components/myStar.jsx

#63 : resize page ratio to 3:7

---

client/components/myStar.jsx

Carousel display begins on the index of selected image

#70: Start Carousel display on image clicked

---

client/components/Nav.jsx
client/css/index.css
client/mainPage.jsx

Underline the tab that user is currently on

#66 : highlight the tab that user is on currently

---

client/components/myStar.jsx
db/celebrity.js
package.json

Get list of names from wiki using crawler
https://en.wikipedia.org/wiki/List_of_South_Korean_idol_groups_(2010s)

#75: crawling wiki and get list of names

---

db/celebrity.js

Change list of celebrity names into schema and insert to the database.
Duplicate check is done by mongoose-unique-validator

#76 : Check if name is in database and insert if not

---

client/components/findStar.jsx
client/css/index.css

searchbox for finding celebrity from the list on find your star page

#78: Make component for search

---

client/css/index.css
client/index.jsx

#81: make front page

---

client/components/Nav.jsx
client/components/myStar.jsx
client/components/searchImage.jsx
client/css/index.css
client/index.jsx
client/mainPage.jsx

gallery view for displaying searched image

#83: New page for displaying searched images in gallery view

---

app.js
client/components/searchImage.jsx
package.json
routes/imageUrls.js
webpack.config.js

Added new route for image extraction
Refactor image size of gallery to width : 1 and height : 1
install puppeteer which is used for image extraction

#84: search images using image extractor and display on gallery

---

client/css/index.css

white underline and text color when toggle nav

#91: Fix navbar toggling effect

---

client/components/NavLink.jsx
client/css/index.css

remove blue bar on carousel view and increase display size

#90: full size image with modal

---

client/components/searchImage.jsx
client/css/index.css

Add favourite button on modal image view

#95: Add favourite button on modal image view 

---

client/components/NavLink.jsx
client/components/searchImage.jsx
client/index.jsx
client/nav.jsx
db/celebrity.js
db/database.js
routes/Favourite.js
routes/imageUrls.js

implement favourite functionality on modal heart button click
isFavourite function checks if selected image is already in the database. 
heart will render as red on modal display if the image is already in the list and vice versa.
setImgAsFavourite function adds/removes image from database based on isFavourite status

#96: Add to database on fav button click

---

client/components/NavLink.jsx
client/components/savedImage.jsx
client/css/index.css

Use modal to make login dialog
if typed user info matches with database, set username to id
if it does not match notify user to sign up

#102: Create modal lonin for user

---

client/components/NavLink.jsx
client/components/savedImage.jsx
client/components/searchImage.jsx
client/css/index.css
client/nav.jsx

Retrieve images saved on the favourite databae according to username

#104: Retrieve favourite list based on username

---

client/components/NavLink.jsx
client/css/index.css
client/index.jsx
client/nav.jsx

Added search bar beside logo,
when new value is submitted, search image page is re-rendered into corresponding celebrity

#106: search bar on nav

---

client/components/NavLink.jsx
client/components/savedImage.jsx
client/css/index.css
client/nav.jsx

visual enhancement on navbar with celebrity name dropdown on search

#108: dropdown on search

---

client/components/NavLink.jsx
package.json
routes/login.js

encrypt userpassword and compare hashed password, display typed passw…ord into stars

#110: encrypt user password and compare hashed password

---

README.md

readme update.
versions, Structure, Description, dependencies are added

#112: Update readMe

---

package.json

run server and client concurrently using npm run start

#118: Run server and client concurrently

---

client/src/component/searchImage.jsx
routes/imageUrls.js

retrieve fewer images to load faster

#122: retrieve 20 images at a time

---

client/src/component/NavLink.jsx
routes/login.js

Prompt sign-in dialog when user tries to access saved image before logging in.

#128: Ask user to sing in before accessing saved tab

---

client/public/index.html
client/src/Home.js
client/src/component/NavLink.jsx
client/src/component/searchImage.jsx
client/src/css/index.css

Display in mobile view when winner width of the window gets smaller than 500
Photo Slide is omitted in mobile view

#129: support mobile devices

---

client/src/component/NavLink.jsx
client/src/css/index.css

navigate dropdown list using arrow Key

#135: support keyboard navigation on auto complete dropdown

---

client/src/Home.js
client/src/component/NavLink.jsx
client/src/css/index.css

Switch the font size from px to rem on front page and navigation bar. 
(px is an absolute measure where rem values are relative to the root html element)
Change dimensions setting on front page to remove white spaces on the bottom
(px to percentages)
Added bottom margin on mobile navigation search bar

#136: use responsive font size

---

client/src/Home.js
client/src/component/NavLink.jsx
client/src/component/savedImage.jsx
client/src/component/searchImage.jsx
client/src/css/index.css

clean up CSS code to have correct format

#133: CSS class clean up

---

client/src/component/searchImage.jsx
client/src/css/index.css

call moreImage after first search to load more images on background
after image loading on background is complete, store those images in state variable 'moreImage' 
when user scrolls down more than 50% of the page, append images in moreImage to displaying gallery then call moreImage again to load more images on background

#130: dynamically loading images
